[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = ""
  exclude = [
    # By file Path
    '**/**/certifications.html'
  ]

package = "netlify-plugin-no-more-404"
  on404 = "error" 
  cacheKey = "MyCacheKey"
  debugMode = false
