[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = ""
  exclude = [
    # By file Path
    '.certifications.html',
    './build-dir/certifications.html',
    '/certifications.html',
    './build-dir/certifications.html',
    '/build-dir/certifications.html'


  ]
  