[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = ""
  exclude = [
    # By file Path
    '**/**/certifications.html'
  ]
  

  [[plugins]]
package = "netlify-plugin-no-more-404"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]
  on404 = "error" 
  cacheKey = "MyCacheKey"
  debugMode = false